g:
  host: 192.168.110.132
  port: 8000
sql:
  host: 127.0.0.1
  port: 3306
  name: root
  password: root
  dbname: ctf
admin:
  name: admin
  password: admin
key:
  hash: abcdefgh
  jwt: a_secret_key